// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package queries

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Page struct {
	ID        pgtype.UUID
	Name      string
	ItemShow  bool
	ItemOrder int32
}

type User struct {
	ID        pgtype.UUID
	Username  string
	Password  string
	CreatedAt time.Time
	UpdatedAt time.Time
}
